setupinfo:
    rbin_loglow: 1.4
    rbin_loghigh: 2
    n_rbins: 20
    nx: 2
    ny: 2
    nz: 2
    lbox: 2100

analysiscuts:
    logmass_lowcut: 13.
    logmass_highcut: 16.

computeinfo:
    numcores: 'max'

outputinfo:
    outfilebase: '/homes/avillarreal/data'


