setupinfo:
    #rbin_loglow: 1.4
    rbin_loglow: 0.7
    #rbin_loghigh: 2
    rbin_loghigh: 2
    n_rbins: 40
    nx: 2
    ny: 2
    nz: 2
    lbox: 2100

analysiscuts:
    logmass_lowcut: 13.
    logmass_highcut: 13.2

computeinfo:
    numcores: 'max'

outputinfo:
    outfilebase: '/homes/avillarreal/repositories/deltasigma'


