setupinfo:
    rbin_loglow: 0.7
    #rbin_loglow: -0.7
    #rbin_loghigh: 2
    rbin_loghigh: 2
    n_rbins: 20
    nx: 3
    ny: 3
    nz: 3
    lbox: 2100

analysiscuts:
    logmass_lowcut: 13.0
    logmass_highcut: 15.0

computeinfo:
    numcores: 'max'

outputinfo:
    outfilebase: '/homes/avillarreal/repositories/deltasigma'


